stages:
    - deploy

deploy_to_test:
    tags:
        - test
    environment:
        name: test
        url: http://186.33.211.247:89/web/index.html
    stage: deploy
    only:
        - test
    script:
        - pkill -f api/api.py
        - cd /var/www/html/simi/api
        - git fetch --all
        - git reset --hard origin/test
        - source .venv/bin/activate
        - .venv/bin/pip install -r requirements.txt
        - python api/api.py simi Simi.T.7102 simidb 192.168.150.101 192.168.150.101 simi Simi.T.7102 jbpmdb &> /tmp/simi_$(date +%Y-%m-%d-%H_%M_%s)

deploy_to_dev:
    tags:
        - test
    environment:
        name: test
        url: http://186.33.211.247:89/web2/index.html
    stage: deploy
    only:
        - /^dev\/.*$/
    script:
        - cd /var/www/html/simi/api
        - git fetch --all
        - git reset --hard origin/$CI_COMMIT_REF_NAME
        - source .venv/bin/activate
        - .venv/bin/pip install -r requirements.txt
        - python api/api.py simi Simi.T.7102 simidb 192.168.150.101 192.168.150.101 simi Simi.T.7102 jbpmdb &> /tmp/simi_$(date +%Y-%m-%d-%H_%M_%s)

deploy_to_prod:
    tags:
        - prod
    environment:
        name: prod
        url: http://186.33.211.125:89/web/index.html
    stage: deploy
    only:
        - master
    when: manual
    script: 
        - cd /var/www/html/simi/api
        - git fetch --all
        - git reset --hard origin/$CI_COMMIT_REF_NAME
        - source .venv/bin/activate
        - .venv/bin/pip install -r requirements.txt
        - python api/api.py simi Simi.PROD.7102 simidb 192.168.150.115 192.168.150.115 simi Simi.PROD.7102 jbpmdb &> /tmp/simi_$(date +%Y-%m-%d-%H_%M_%s)



